### ISSUE TITLE
invalid conversion from 'int' to 'uart_port_t'

### ISSUE THREAD

**Issue by entorb** [christian-heusel/esp32-smartMeter#3]
Hi, giving it a first try, this type errors is reported:

```
.../components/uart-communication/uart-communication.cc:20:43: error: invalid conversion from 'int' to 'uart_port_t' [-fpermissive]
```

**Comment by christian-heusel** [comment]
This project now works a while for us, I guess the latest version of the esp sdk has changed some interface type 🤔

**Comment by Heusel** [comment]
Hm...  We clone the system again (please use the _--reverse_ switch to clone also the external components) and rebuild did not show the reported error. Just some not spectacle warnings. 
Which UART you define in the menuconfig? 
We work in a  Linux environment.

**Comment by christian-heusel** [comment]
I was able to reproduce the error by setting up the latest version of the ESP idf (5.2.1) again. One possible fix is to put a cast in front of every `UART_COMMUNICATION_PORT_NUM` usage like so:
```diff
-        uart_write_bytes(UART_COMMUNICATION_PORT_NUM, teststring.data(), teststring.size());
+        uart_write_bytes((uart_port_t)UART_COMMUNICATION_PORT_NUM, teststring.data(), teststring.size());
```
but thats not really a great solution. Maybe we should initialize the value inside of the class once from the macro value and convert it on initialization to the appropriate type `uart_port_t`.

**Comment by Heusel** [comment]
Can confirm your  [comment](https://github.com/christian-heusel/esp32-smartMeter/issues/3#issuecomment-1991019641) Christian. Update to the latest version v5.2.1 give me the same result.
Type checking  now need a value from type uart_port_t and can normaly taken from header file.

`const uart_port_t  uart_num = UART_NUM_2;`

At the moment I don't know how that could be solved in Kconfig file inside the uart component. 
So I confirm the solution from Christian but prefer the cast at the first usage in the define.
```
-#define UART_COMMUNICATION_PORT_NUM      (CONFIG_UART_PORT_NUM)
+#define UART_COMMUNICATION_PORT_NUM     (uart_port_t)(CONFIG_UART_PORT_NUM)
```
maybe we will find a smarter solution in the future.

**Comment by entorb** [comment]
works, thank you so much!
